/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    'contact-request': ContactRequest;
    media: Media;
    'car-fleet': CarFleet;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'contact-section': ContactSection;
    hero: Hero;
    'services-section': ServicesSection;
    'car-fleet-section': CarFleetSection;
    'opinion-section': OpinionSection;
    'realizations-section': RealizationsSection;
    'faq-section': FAQSection;
    'about-us-header': AboutUsHeader;
    'about-us-overview': AboutUsOverview;
    'about-us-statistics': AboutUsStatistic;
    'about-us-team': AboutUsTeam;
    'car-fleet-header': CarFleetHeader;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-request".
 */
export interface ContactRequest {
  id: number;
  email: string;
  firstName: string;
  phoneNumber: string;
  car: number | CarFleet;
  date: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-fleet".
 */
export interface CarFleet {
  id: number;
  image: number | Media;
  name: string;
  price: number;
  details: {
    hp: number;
    transmission: 'manual' | 'sequential' | 'automatic';
    seats: number;
    fuel: 'gasoline' | 'diesel' | 'lpg' | 'hybrid';
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  title: string;
  label?: string | null;
  image: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  title: {
    firstPart: string;
    secondPart: string;
  };
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section".
 */
export interface ServicesSection {
  id: number;
  title: string;
  label?: string | null;
  reelSection: {
    title: string;
    label?: string | null;
    video: number | Media;
    isHidden: boolean;
  };
  services: {
    title: string;
    content: string;
    isNew: boolean;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-fleet-section".
 */
export interface CarFleetSection {
  id: number;
  title: string;
  label?: string | null;
  cars: (number | CarFleet)[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinion-section".
 */
export interface OpinionSection {
  id: number;
  title: string;
  label?: string | null;
  opinions: {
    image: number | Media;
    fullName: string;
    content: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realizations-section".
 */
export interface RealizationsSection {
  id: number;
  title: string;
  label?: string | null;
  realizations: {
    video: number | Media;
    title: string;
    description: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section".
 */
export interface FAQSection {
  id: number;
  title: string;
  label?: string | null;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-header".
 */
export interface AboutUsHeader {
  id: number;
  title: string;
  label?: string | null;
  content: string;
  subContent?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-overview".
 */
export interface AboutUsOverview {
  id: number;
  video: number | Media;
  title: string;
  subTitle: string;
  content: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-statistics".
 */
export interface AboutUsStatistic {
  id: number;
  title: string;
  label?: string | null;
  statistics: {
    clients: number;
    kilometers: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-team".
 */
export interface AboutUsTeam {
  id: number;
  title: string;
  label?: string | null;
  team: {
    image: number | Media;
    firstName: string;
    description: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "car-fleet-header".
 */
export interface CarFleetHeader {
  id: number;
  title: string;
  label?: string | null;
  content: string;
  subContent?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}